language: java
jdk:
  # junit5 requires java 8
  - oraclejdk8
  #- oraclejdk9

addons:
    sonarcloud:
        organization: "robstoll-github"
        token:
            secure: $SONAR_TOKEN


before_install:
 - chmod +x gr
install: true

script:
  - ./gr -i build
  - sonar-scanner
    -X
    -Dsonar.projectKey=robstoll_tutteli-spek-extensions
    -Dsonar.sources=src
    -Dsonar.projectVersion=0.4.0-SNAPSHOT
    -Dsonar.jacoco.reportMissing.force.zero=true
    -Dsonar.jacoco.reportPaths=build/jacoco/junitPlatformTest.exec
    -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/report.xml
    -Dsonar.verbose=true
  - head -c 200 build/jacoco/junitPlatformTest.exec
  - head -c 200 build/reports/jacoco/report.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
    - $HOME/.sonar/cache
